### ISSUE TITLE
Error: inject()

### ISSUE THREAD

**Issue by mmoua17** [angular-studio/wooApi#12]
Trying to get this work following your doc, but getting this error and not sure is this something in my project or version issue, is this working with the latest Angular version?

ERROR Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:4717)
    at Module.ɵɵinject (core.js:4727)
    at Object.WoocommerceProductsService_Factory [as factory] (ngx-wooapi.js:311)
    at R3Injector.hydrate (core.js:11341)
    at R3Injector.get (core.js:11162)
    at NgModuleRef$1.get (core.js:24302)
    at Object.get (core.js:23999)
    at getOrCreateInjectable (core.js:4169)
    at Module.ɵɵdirectiveInject (core.js:14703)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:9)
defaultErrorLogger @ core.js:4442
handleError @ core.js:4490
(anonymous) @ core.js:28205
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:27472
(anonymous) @ core.js:28205
invoke @ zone-evergreen.js:364
onInvoke @ core.js:27545
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:27533
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
then @ zone-evergreen.js:979
bootstrapModule @ core.js:28133
zUnb @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.js:11
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1

**Comment by prosenjit-manna** [comment]
Yes it is working with latest version. You can try to run and see this from https://stackblitz.com/edit/ngx-wooapi?file=package.json

- You dont have to put the service in providers list. That is already done by 

@Injectable({
  providedIn: 'root'
})

Also you can use services from directly download and check once.
I think it is not releated with this npm 

Please check once this related issue too: https://github.com/angular/angular/issues/25813

**Comment by mmoua17** [comment]
@prosenjit-manna 
Thank you for the reply, using it directly seems to work!
