### ISSUE TITLE
angular 12 compatibility

### ISSUE THREAD

**Issue by perspicuous** [angular-studio/wooApi#13]
is there any plan to make this package work with angular 12?
Thank you
Timur

**Comment by prosenjit-manna** [comment]
Okay. I  will check this weekend.

**Comment by prosenjit-manna** [comment]
Published. Enjoy :)

**Comment by perspicuous** [comment]
Thank you. 

Is it a bug, that it appends "/http:/localhost:8080/api/" 

making the request looking like:

xxxxxx.com/appwoo/http:/localhost:8080/api/category

**Comment by prosenjit-manna** [comment]
Probably you did not set up env and interceptor properly.

Thanks & Regards,
Prosenjit Manna
Itobuz Technologies Pvt Ltd.
