### ISSUE TITLE
StaticInjectorError(Platform: core)[WoocommerceProductsService -> HttpClient]:

### ISSUE THREAD

**Issue by Ruslancic** [angular-studio/wooApi#3]
I have this issue in Angular 7, after adding wooservice on my component!
I know, this is for Angular 6, btw, i want to ask, if can you upgrade it for 7 version?
And i have this warnings in the console:

<pre>WARNING in ./node_modules/ngx-wooapi/node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ngx-wooapi/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression </pre>

<pre>
"@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2" </pre>

**Comment by prosenjit-manna** [comment]
I will release a new version!

**Comment by prosenjit-manna** [comment]
Updated dependency, Check this version https://www.npmjs.com/package/ngx-wooapi/v/7.0.0-beta.2.
